title:              Viktoryia Khlystun
email:              vika95vika@gmail.com
description:        Заметки обо всем на свете
author:             Viktoryia Khlystun
baseurl:            "/blog"
url:                "https://vika95viktoria.github.io/blog/"

# Social Profiles
twitter_username:   
github_username:    vika95viktoria
facebook_username:  
instagram_username:  vika_khlystun
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-0Z1LGVJGL8 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
